# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaySteps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaySteps

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
  pod 'CryptoSwift'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'PayStepsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayStepsUITests' do
    # Pods for testing
  end

end
